"use client";
import * as React from "react";
import type { AttendanceStatus, StaffAttendanceRecord, StaffMember } from "@minarvabiz/types";
import { Button } from "../Button";
import { inputClass, selectClass } from "../forms/FormField";

const statuses: Array<{value:AttendanceStatus;label:string}>=[{value:"present",label:"Present"},{value:"absent",label:"Absent"},{value:"half_day",label:"Half day"},{value:"leave",label:"Leave"},{value:"holiday",label:"Holiday"}];

export function AttendanceGrid({staff,rows,month,onMonthChange,onMark,onMarkAllToday}:{staff:StaffMember[];rows:StaffAttendanceRecord[];month:string;onMonthChange:(v:string)=>void;onMark:(staffId:string,date:string,status:AttendanceStatus)=>void;onMarkAllToday:(status:AttendanceStatus)=>void;}){
 const days=React.useMemo(()=>{const [y,m]=month.split("-").map(Number);return Array.from({length:new Date(y,m,0).getDate()},(_,i)=>String(i+1).padStart(2,"0"));},[month]);
 const byKey=React.useMemo(()=>new Map(rows.map(r=>[`${r.staffId}|${r.date}`,r])),[rows]);
 const sums=React.useMemo(()=>{const map=new Map<string,{p:number;a:number;h:number;l:number;ot:number}>();for(const r of rows){const v=map.get(r.staffId)??{p:0,a:0,h:0,l:0,ot:0};if(r.status==="present")v.p++;else if(r.status==="absent")v.a++;else if(r.status==="half_day")v.h++;else if(r.status==="leave")v.l++;v.ot+=r.overtimeMinutes;map.set(r.staffId,v);}return map;},[rows]);
 return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Attendance Grid</h1><p className="text-sm text-slate-500">Offline-first daily attendance with audit and hybrid sync.</p></div><div className="flex flex-wrap gap-2"><input aria-label="Attendance month" type="month" className={inputClass} value={month} onChange={e=>onMonthChange(e.target.value)}/><Button variant="outline" onClick={()=>onMarkAllToday("present")}>All present today</Button><Button variant="outline" onClick={()=>onMarkAllToday("holiday")}>Holiday today</Button></div></div><div className="overflow-auto rounded-xl border bg-white"><table className="min-w-max text-sm"><thead><tr className="border-b bg-slate-50"><th className="sticky left-0 z-10 bg-slate-50 p-2 text-left">Staff</th>{days.map(d=><th key={d} className="p-2">{d}</th>)}<th>P</th><th>A</th><th>HD</th><th>L</th><th>OT</th></tr></thead><tbody>{staff.map(member=>{const t=sums.get(member.id);return <tr key={member.id} className="border-b"><th className="sticky left-0 bg-white p-2 text-left">{member.name}</th>{days.map(day=>{const date=`${month}-${day}`;const row=byKey.get(`${member.id}|${date}`);return <td key={day} className="p-1"><select aria-label={`${member.name} attendance ${date}`} className={selectClass+" min-w-24 py-1"} value={row?.status||""} onChange={e=>e.target.value&&onMark(member.id,date,e.target.value as AttendanceStatus)}><option value="">—</option>{statuses.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></td>})}<td className="p-2">{t?.p||0}</td><td className="p-2">{t?.a||0}</td><td className="p-2">{t?.h||0}</td><td className="p-2">{t?.l||0}</td><td className="p-2">{t?.ot||0}m</td></tr>})}</tbody></table>{!staff.length&&<p className="p-6 text-center text-sm text-slate-500">Add active staff to start attendance.</p>}</div></div>;
}
