import assert from "node:assert/strict";
import fs from "node:fs";
import { createRequire } from "node:module";
const require=createRequire(import.meta.url);const ts=require("typescript");
require.extensions[".ts"]=(module,filename)=>module._compile(ts.transpileModule(fs.readFileSync(filename,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);
const permissions=require("../permissions.ts");const phase6=require("../phase6-store.ts");const persistence=require("../persistence.ts");const phase6Schema=require("../../../database/src/schema/phase6.ts");
permissions.setCurrentRole("admin");permissions.setRuntimeFeaturePolicy(null);
const staff={id:"attendance-staff-1",name:"Asha",role:"staff",salary:10000,status:"active",createdAt:"2026-10-01T00:00:00.000Z",updatedAt:"2026-10-01T00:00:00.000Z"};
phase6.hydratePhase6({staff:[staff],attendance:[],assignments:[],incentiveRules:[],payouts:[],notifications:[]});
const created=phase6.setAttendance({staffId:staff.id,date:"2026-10-08",status:"present",overtimeMinutes:45});
assert.equal(created.status,"present");assert.equal(created.overtimeMinutes,45);
assert.equal(phase6.listAttendance({staffId:staff.id,from:"2026-10-01",to:"2026-10-31"}).length,1);
const updated=phase6.setAttendance({staffId:staff.id,date:"2026-10-08",status:"half_day",breakMinutes:30,overtimeMinutes:0});
assert.equal(updated.id,created.id);assert.equal(updated.status,"half_day");assert.equal(phase6.listAttendance().length,1);
phase6.setAttendance({staffId:staff.id,date:"2026-10-09",status:"leave"});
const summary=phase6.attendanceSummary("2026-10-01","2026-10-31").get(staff.id);
assert.deepEqual(summary,{present:0,absent:0,halfDay:1,leave:1,holiday:0,overtimeMinutes:0});
const snapshot=phase6.exportPhase6State();assert.equal(snapshot.attendance.length,2);
phase6.hydratePhase6({attendance:[]});assert.equal(phase6.listAttendance().length,0);
phase6.hydratePhase6({attendance:snapshot.attendance});assert.equal(phase6.listAttendance().length,2);
assert.throws(()=>phase6.setAttendance({staffId:staff.id,date:"08-10-2026",status:"present"}),/YYYY-MM-DD/);
assert.throws(()=>phase6.setAttendance({staffId:"missing",date:"2026-10-08",status:"present"}),/Staff not found/);
assert.equal(persistence.SNAPSHOT_VERSION,13);assert.ok(phase6Schema.PHASE6_TABLES.includes("staff_attendance"));\nconsole.log("Attendance runtime behavior PASS");
