import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const source=fs.readFileSync('apps/web/src/lib/data-source.ts','utf8');
assert.match(source,/"\/attendance"/, 'attendance loads real staff on direct navigation');
const require=createRequire(import.meta.url),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
assert.match(source,/"\/attendance"/, 'attendance loads real staff on direct navigation');
assert.match(source,/"staff_attendance"/, 'attendance is hydrated from PostgreSQL');
const {createSupabaseCloudAdapter}=require('../../../sync/src/supabase-adapter.ts');
const inserts=[],pulls=[];
const client={async insert(table,row){inserts.push({table,row});return{error:null};},async update(){return{error:null};},async select(table,query){pulls.push({table,query});return{data:[],error:null};}};
const adapter=createSupabaseCloudAdapter(client,'device-1');
const payload={staffId:'staff-1',date:'2026-10-08',status:'present',breakMinutes:30,overtimeMinutes:45,clockIn:null,clockOut:null,version:1,createdAt:'2026-10-08T00:00:00Z',updatedAt:'2026-10-08T00:00:00Z'};
const result=await adapter.push([{id:'event-1',aggregateType:'staff_attendance',aggregateId:'att-1',eventType:'insert',payload,sequence:1,occurredAt:payload.createdAt}]);
assert.deepEqual(result.accepted,['event-1']);
const row=inserts.find(i=>i.table==='staff_attendance').row;
assert.equal(row.staff_id,'staff-1');assert.equal(row.attendance_date,'2026-10-08');assert.equal(row.break_minutes,30);assert.equal(row.staffId,undefined);
await adapter.pull('2026-10-01T00:00:00Z','device-1');
assert.ok(pulls.some(p=>p.table==='staff_attendance'));
console.log('Attendance online parity PASS');
