import assert from "node:assert/strict";
import fs from "node:fs";
const ui=fs.readFileSync("packages/ui/src/components/staff/RosterPlanner.tsx","utf8");
const wrapper=fs.readFileSync("apps/desktop/src/components/DesktopRosterPanel.tsx","utf8");
const app=fs.readFileSync("apps/desktop/src/App.tsx","utf8");
const exportSource=fs.readFileSync("packages/ui/src/index.ts","utf8");
assert.match(ui,/planRecurringRoster\(/,"Shared monthly preview reuses the validated planning engine");
assert.match(ui,/Preview only: no changes were saved/,"No unapproved batch execution");
assert.match(ui,/expectedVersion: current\?\.version/,"Corrections preserve optimistic version checks");
assert.match(ui,/expectedVersion: slot.version/,"Cancellation requires the reviewed revision");
assert.match(ui,/window.confirm\(/,"Cancellation is explicitly confirmed");
assert.match(ui,/Branch-local dates and times/,"Time-zone policy limitation is exposed");
assert.match(wrapper,/can\("staff.manage"\)/,"Unauthorized staff access is rejected");
assert.match(wrapper,/await onChanged\(\)/,"Windows mutations await strict SQLite save");
assert.match(wrapper,/phase6Store.assignRosterSlot/,"Assignments use the audited domain");
assert.match(wrapper,/phase6Store.updateShiftRule/,"Template edits use the audited domain");
assert.match(app,/Open Shift & Roster Planner/,"Planner is reachable from actual Windows staff navigation");
assert.match(exportSource,/components\/staff\/RosterPlanner/,"Shared component is exported");
console.log("HR-004 Windows roster planner UI wiring and safety contract PASS");
