import assert from "node:assert/strict";
import fs from "node:fs";

const sql=fs.readFileSync("supabase/migrations/20261009_hr_roster_event_authority.sql","utf8");
const order=fs.readFileSync("supabase/MIGRATION_ORDER.txt","utf8").trim().split(/\r?\n/).filter(Boolean);
const workflow=fs.readFileSync(".github/workflows/first-admin-fresh-instance-e2e.yml","utf8");
assert.equal(order.at(-1),"20261009_hr_roster_event_authority.sql");
assert.match(sql,/CREATE TABLE IF NOT EXISTS public\.staff_roster_event_receipts/);
assert.match(sql,/CREATE OR REPLACE FUNCTION public\.apply_staff_roster_event/);
assert.match(sql,/SECURITY DEFINER/);
assert.match(sql,/current_user_authorization\(\)/,"Tenant and role must derive from server-side membership");
assert.match(sql,/auth_role NOT IN \('super_admin','admin','manager'\)/);
assert.match(sql,/pg_advisory_xact_lock/);
assert.match(sql,/prior_receipt\.request_json <> p_record/,"Replay identity must bind to original payload");
assert.match(sql,/prior_receipt\.device_id <> p_device_id/,"Replay must bind device");
assert.match(sql,/prior_receipt\.sequence <> p_sequence/,"Replay must bind ordered sequence");
assert.match(sql,/previous_slot\.version \+ 1/,"Roster updates must be revision-checked");
assert.match(sql,/previous_shift\.version \+ 1/,"Shift updates must be revision-checked");
assert.match(sql,/previous_slot\.branch_id/,"Historical branch must remain immutable");
assert.match(sql,/INSERT INTO public\.staff_roster_event_receipts/);
assert.match(sql,/INSERT INTO public\.audit_logs/,"Event and audit must commit in the same PostgreSQL transaction");
assert.match(sql,/REVOKE ALL ON public\.staff_roster_event_receipts FROM PUBLIC, anon, authenticated/);
assert.match(sql,/GRANT EXECUTE ON FUNCTION public\.apply_staff_roster_event\(TEXT,JSONB,UUID,TEXT,BIGINT\)\s+TO authenticated/);
assert.doesNotMatch(sql,/GRANT (INSERT|UPDATE|DELETE).* TO authenticated/);
assert.match(workflow,/node scripts\/hr-roster-events-e2e\.mjs/,"Fresh-instance CI must execute real roster SQL transactions");
const runner=fs.readFileSync("scripts/hr-roster-events-e2e.mjs","utf8");
assert.match(runner,/isolated local Supabase database/);
const fixtures=fs.readFileSync("scripts/hr-roster-events-e2e.sql","utf8");
assert.match(fixtures,/ROLLBACK;/);
assert.match(fixtures,/Tampered retry accepted/);
assert.match(fixtures,/Overnight overlap accepted/);
assert.match(fixtures,/Stale roster revision/);
assert.match(fixtures,/Direct authenticated roster insert accepted/);
assert.match(fixtures,/Cashier wrote shift via RPC/);
assert.match(fixtures,/Cross tenant read allowed/);
console.log("HR roster audited mutation contract PASS");
