import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../../..");
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");

const updater = read("apps/desktop/electron/updater.ts");
const desktopMain = read("apps/desktop/electron/main.ts");
const settingsPanel = read("packages/ui/src/components/settings/SettingsPanel.tsx");
const dashboard = read("packages/ui/src/components/dashboard/Dashboard.tsx");
const updateNotice = read("packages/ui/src/components/dashboard/SoftwareUpdateNotice.tsx");
const config = read("apps/desktop/scripts/write-update-config.mjs");
const route = read("infra/cloudflare-license-edge/src/index.js");
const signing = read("apps/license-admin/src/lib/signing-key.ts");
const deep = read(".github/workflows/windows-deep-smoke.yml");
const release = read(".github/workflows/release-windows.yml");
const publisher = read(".github/workflows/publish-windows-release.yml");
const pkg = JSON.parse(read("apps/desktop/package.json"));
const rootPkg = JSON.parse(read("package.json"));
const releaseNotes = JSON.parse(read("release-notes.json"));

assert.match(pkg.version, /^\d+\.\d+\.\d+$/);
assert.equal(pkg.version, rootPkg.version);
assert.ok(Array.isArray(releaseNotes[pkg.version]) && releaseNotes[pkg.version].length > 0, `release-notes.json is missing notes for ${pkg.version}`);
assert.match(updater, /minarvabiz-update-v1/);
assert.match(updater, /github\.com/);
assert.match(updater, /evertekitsolutions-del\/minarvabiz\/releases\/download/);
assert.match(updater, /16 \* 1024/);
assert.match(dashboard, /SoftwareUpdateNotice/);
assert.match(updateNotice, /checkForUpdates/);
assert.match(updateNotice, /Update available/);
assert.match(updateNotice, /What&apos;s new/);
assert.match(updateNotice, /Update & restart/);
assert.match(updateNotice, /sessionStorage/);
assert.match(settingsPanel, /What's new in|What&apos;s new in/);
assert.match(desktopMain, /spawn\(update\.path, \["--updated", "\/S", "--force-run"\]/);
assert.match(desktopMain, /windowsHide: true/);
assert.match(desktopMain, /app\.quit\(\)/);
assert.match(settingsPanel, /Update & restart/);
assert.match(settingsPanel, /install silently and reopen automatically/);
assert.equal(settingsPanel.includes("Install update safely"), false);
assert.match(config, /MINARVA_LICENSE_PUBLIC_KEY_HEX/);
assert.equal(route.includes("api.github.com"), false);
assert.equal(route.includes("releases/latest"), false);
assert.equal(route.includes("package.json"), true);
assert.equal(route.includes("releases/download"), true);
assert.equal(route.includes(".sha256"), true);
assert.equal(route.includes("rootPackage.version"), true);
assert.match(route, /release-notes\.json/);
assert.match(route, /notesForVersion/);
assert.match(route, /signTextBase64Url/);
assert.match(route, /MinarvaBiz-Setup-/);
assert.match(signing, /signTextBase64Url/);
assert.match(deep, /MINARVA_UPDATE_MANIFEST_URL/);
assert.match(release, /MINARVA_UPDATE_MANIFEST_URL/);
assert.match(release, /contents: read/);
assert.match(publisher, /workflow_run/);
assert.match(publisher, /contents: write/);
assert.match(publisher, /gh release create/);
assert.match(publisher, /MinarvaBiz-update-manifest\.json/);
assert.match(publisher, /gh release upload/);
assert.match(publisher, /release-notes\.json/);
assert.match(publisher, /--notes-file release-notes\.md/);

console.log("Secure Windows update channel contract PASS");
