import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../../..");
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");

const nav = read("packages/ui/src/lib/nav.ts");
const ui = read("packages/ui/src/components/support/SupportCenter.tsx");
const server = read("apps/web/src/lib/support-server.ts");
const chatRoute = read("apps/web/src/app/api/support/chat/route.ts");
const feedbackRoute = read("apps/web/src/app/api/support/feedback/route.ts");
const healthRoute = read("apps/web/src/app/api/support/health/route.ts");
const broker = read("supabase/functions/minarva-support-broker/index.ts");
const webMiddleware = read("apps/web/src/middleware.ts");
const adminEdge = read("infra/cloudflare-license-edge/src/index.js");
const adminInbox = read("apps/license-admin/src/app/admin-panel/SupportInboxCard.tsx");
const migration = read("supabase/migrations/20260927_ai_support_center.sql");
const runtimeConfigMigration = read("supabase/migrations/20261001_support_runtime_config.sql");
const freeAiWorker = read("infra/cloudflare-ai-worker/src/index.js");
const freeAiWrangler = read("infra/cloudflare-ai-worker/wrangler.jsonc");
const zeroCostArchitecture = read("docs/ZERO_COST_GROWTH_ARCHITECTURE.md");
const release = read(".github/workflows/release-windows.yml");
const docs = read("docs/AI_SUPPORT_CENTER.md");

assert.match(nav, /"support"/);
assert.match(nav, /AI Support Center/);

assert.match(ui, /AI Technical Support/);
assert.match(ui, /Ideas & Feature Requests/);
assert.match(ui, /Attach screenshot/);
assert.match(ui, /Share redacted diagnostics/);
assert.match(ui, /Escalate to Support/);
assert.match(ui, /Send to Product Team/);
assert.match(ui, /compressScreenshot/);
assert.match(ui, /license token/i);

assert.match(server, /cloudflare-workers-ai/);
assert.match(server, /MINARVA_FREE_AI_URL/);
assert.match(server, /MINARVA_ALLOW_PAID_AI_FALLBACK/);
assert.match(server, /paidAiFallbackEnabled/);
assert.match(server, /free_quota_exhausted/);
assert.match(server, /runtime-config/);
assert.match(server, /ai-gateway\.vercel\.sh\/v1\/responses/);
assert.match(server, /api\.openai\.com\/v1\/responses/);
assert.match(server, /input_image/);
assert.match(server, /VERCEL_OIDC_TOKEN/);
assert.match(server, /OPENAI_API_KEY/);
assert.match(server, /MINARVA_SUPPORT_AI_MODEL/);
assert.match(server, /openai\/gpt-5\.4-mini/);
assert.match(server, /zeroDataRetention: true/);
assert.match(server, /disallowPromptTraining: true/);
assert.match(server, /String\(process\.env\.MINARVA_ALLOW_PAID_AI_FALLBACK \|\| ""\)/);
assert.match(server, /READINESS_PROBE_IMAGE/);
assert.match(server, /aiOperational/);
assert.match(server, /submissionConfigured/);
assert.match(server, /billing_or_quota/);
assert.match(server, /You can still send this conversation to Minarva Biz Support/);
assert.match(server, /docs\/FINAL_COMPLETION\.md/);
assert.match(server, /GitHub latest release/);
assert.match(server, /GitHub recent main commits/);
assert.match(server, /minarva-support-broker/);
assert.doesNotMatch(server, /SUPPORT_RATE_LIMIT_SECRET/);
assert.doesNotMatch(server, /SUPABASE_SERVICE_ROLE_KEY/);
assert.match(server, /Never ask for or expose license tokens/);
assert.equal(server.includes("NEXT_PUBLIC_OPENAI"), false);

assert.match(broker, /createRemoteJWKSet/);
assert.match(broker, /jwtVerify/);
assert.match(broker, /team_I74uWi3aeWhymbb4apEZ3nnq/);
assert.match(broker, /prj_GgZIaN5Q1SqS5oU5Ax89z4itcust/);
assert.match(broker, /environment:production/);
assert.match(broker, /SUPABASE_SERVICE_ROLE_KEY/);
assert.match(broker, /support-chat-minute/);
assert.match(broker, /support-chat-hour/);
assert.match(broker, /support-submit-day/);
assert.match(broker, /consume_license_rate_limit/);
assert.match(broker, /support_requests/);
assert.match(broker, /support-rate/);
assert.match(broker, /support-client/);
assert.match(broker, /op === "readiness"/);
assert.match(broker, /support-readiness/);
assert.match(broker, /submissionWrite/);
assert.match(broker, /Synthetic readiness probe/);
assert.match(broker, /SUPPORT_RETENTION_DAYS = 180/);
assert.match(broker, /purgeExpiredSupportRequests/);
assert.match(broker, /op === "runtime-config"/);
assert.match(broker, /support_runtime_config/);
assert.match(broker, /runtimeConfig/);

assert.match(chatRoute, /support-chat-minute/);
assert.match(chatRoute, /support-chat-hour/);
assert.match(chatRoute, /answerTechnicalSupport/);
assert.match(feedbackRoute, /support-submit-day/);
assert.match(feedbackRoute, /createSupportRequest/);
assert.match(feedbackRoute, /triageSupportRequest/);
assert.match(healthRoute, /supportConfigurationStatus/);
assert.match(healthRoute, /await supportConfigurationStatus/);
assert.match(healthRoute, /ready/);
assert.match(healthRoute, /status\.aiOperational/);
assert.match(healthRoute, /status\.submissionConfigured/);
assert.match(healthRoute, /status\.runtimeConfigConfigured/);
assert.match(healthRoute, /status\.retentionConfigured/);
assert.equal(webMiddleware.includes('request.nextUrl.pathname.startsWith("/api/support/")'), true);
assert.match(webMiddleware, /method === "POST"/);

assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.support_requests/);
assert.match(migration, /ENABLE ROW LEVEL SECURITY/);
assert.match(migration, /REVOKE ALL ON TABLE public\.support_requests FROM PUBLIC, anon, authenticated/);
assert.match(migration, /GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public\.support_requests TO service_role/);
assert.match(migration, /feature_request/);
assert.match(migration, /technical_escalation/);

assert.match(runtimeConfigMigration, /CREATE TABLE IF NOT EXISTS public\.support_runtime_config/);
assert.match(runtimeConfigMigration, /REVOKE ALL ON TABLE public\.support_runtime_config FROM PUBLIC, anon, authenticated/);
assert.match(runtimeConfigMigration, /GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public\.support_runtime_config TO service_role/);
assert.match(runtimeConfigMigration, /cloudflare-workers-ai/);
assert.match(runtimeConfigMigration, /"enabled", false|'enabled', false/);

assert.match(adminEdge, /cloudflare_admin_list_support_requests/);
assert.match(adminEdge, /cloudflare_admin_update_support_request/);
assert.match(adminInbox, /Support Inbox/);
assert.match(adminInbox, /AI triage/);
assert.match(adminInbox, /Internal notes/);

assert.match(release, /VITE_SUPPORT_API_URL/);
assert.match(release, /https:\/\/minarvabiz-steel\.vercel\.app/);

assert.match(docs, /does not persist raw screenshot bytes/i);
assert.match(docs, /Viewer: read-only Support Inbox/);
assert.match(docs, /Vercel OIDC/);
assert.match(docs, /no OpenAI API key/i);
assert.match(docs, /does not use that content to train/i);
assert.match(docs, /180 days/);
assert.match(docs, /x-vercel-oidc-token/);
assert.match(docs, /--no-verify-jwt/);
assert.match(docs, /configured credential by itself/i);
assert.match(docs, /provider-neutral AI adapter/i);
assert.match(docs, /MINARVA_ALLOW_PAID_AI_FALLBACK/);
assert.match(docs, /Cloudflare Workers AI/i);

assert.match(freeAiWorker, /@cf\/zai-org\/glm-4\.7-flash/);
assert.match(freeAiWorker, /@cf\/google\/gemma-4-26b-a4b-it/);
assert.match(freeAiWorker, /RSASSA-PKCS1-v1_5/);
assert.match(freeAiWorker, /EXPECTED_SUBJECT/);
assert.match(freeAiWorker, /PROJECT_ID/);
assert.match(freeAiWorker, /free_quota_exhausted/);
assert.match(freeAiWorker, /type: "image_url"/);
assert.match(freeAiWorker, /image_url: \{ url: image \}/);
assert.match(server, /iVBORw0KGgoAAAANSUhEUgAAABAAAAAQ/);
assert.match(freeAiWrangler, /"binding": "AI"/);

assert.match(zeroCostArchitecture, /25 paying customers/i);
assert.match(zeroCostArchitecture, /no automatic upgrade to a paid cloud plan/i);
assert.match(zeroCostArchitecture, /self-host/i);
assert.match(zeroCostArchitecture, /MINARVA_ALLOW_PAID_AI_FALLBACK=true/);

console.log("AI Support Center contract PASS");
